parameters:
    octave.sitemap.path: 'sitemap.xml'
    octave.sitemap.host: ~

services:

    octave.sitemap.generator:
        class: Octave\SitemapBundle\Service\SitemapGenerator
        arguments:
            - '@templating'
            - '%kernel.root_dir%'
            - '%octave.sitemap.path%'