parameters:
    octave.sitemap.path: 'sitemap.xml'
    octave.sitemap.host: ~
    octave.sitemap.root_dir: '%kernel.project_dir%'

services:

    Octave\SitemapBundle\Command\GenerateCommand:
        tags: ['console.command']
        arguments:
            - '@octave.sitemap.generator'

    octave.sitemap.generator:
        class: Octave\SitemapBundle\Service\SitemapGenerator
        public: true
        arguments:
            - '@twig'
            - '%octave.sitemap.root_dir%'
            - '%octave.sitemap.path%'
            - '%octave.sitemap.host%'
