parameters:
    octave.sitemap.path: 'sitemap.xml'
    octave.sitemap.host: ~
    octave.sitemap.rood_dir: '%kernel.root_dir%'

services:

    Octave\SitemapBundle\Command\GenerateCommand:
        tags: ['console.command']

    octave.sitemap.generator:
        class: Octave\SitemapBundle\Service\SitemapGenerator
        public: true
        arguments:
            - '@templating'
            - '%octave.sitemap.rood_dir%'
            - '%octave.sitemap.path%'
            - '%octave.sitemap.host%'
